myblog/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('categories/', views.categories, name='categories'),
    path('tags/', views.tags, name='tags'),
]

myblog/apps/authorization/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'authorization'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', LogoutView.as_view(next_page='articles:index'), name='logout'),
    path('register/', views.register, name='register'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('authorization.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

myblog/apps/articles/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Category(models.Model):
    name = models.CharField('Название категории', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField('Название тега', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Author(models.Model):
    image = models.CharField('Фото автора', max_length=255, default='blog-avatar-1.png')
    name = models.CharField('Имя автора', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Article(models.Model):
    image = models.CharField('Фото статьи', max_length=255, default='blog-img-1.jpg')
    title = models.CharField('Название статьи', max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    tag1 = models.ForeignKey(Tag, on_delete=models.CASCADE, default=1)
    # tag2 = models.ForeignKey(Tag, on_delete=models.CASCADE)
    # tag3 = models.ForeignKey(Tag, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Дата публикации')
    text = models.TextField('Текс статьи')
    author_name = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    views = models.IntegerField('Просмотры', default=0)
    is_draft = models.BooleanField('Черновик', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length=50)
    comment_text = models.CharField('Текст комментария', max_length=200)
    pub_date = models.DateTimeField('Дата публикации комментария', default=datetime.now())
    email = models.CharField('Почта', max_length=255, default='unknow@mail.ru')

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

myblog/apps/authorization/models.py
from django.db import models

# Create your models here.

myblog/apps/authorization/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

myblog/apps/articles/views.py
from django.shortcuts import render
from .models import Article, Category, Tag
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage


@login_required()
def index(request):
    # ?Все статьи которые не являются черновиком
    latest_articles_list = Article.objects.filter(is_draft=False).order_by('-pub_date')
    # ?Пагинация для статей
    p = Paginator(latest_articles_list, 3)
    page_num = request.GET.get('page', 1)
    total_pages = p.num_pages  # *Это нужно для того чтобы понять, отображать нам пагинацию или нет
    # !Проверяем, существует страница или нет. На случай если человек будет играться с адресной строкой браузера
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)

    # ?Популярные статьи для сайдбара
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    # ?Категории для сайдбара
    latest_category_list = Category.objects.order_by('name')[:5]
    # ?Теги для сайдбара
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'total_pages': total_pages,
        'latest_articles_list': page,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/blog.html', context)


@login_required()
def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
        a.views = a.views + 1
        a.save()
    except:
        raise Http404("Статья не найдена!")

    latest_comment_list=a.comment_set.order_by('-id')[:10]
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    latest_category_list = Category.objects.order_by('name')[:5]
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'article': a,
        'latest_comment_list': latest_comment_list,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/blog-single.html', context)


@login_required()
def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'], email=request.POST['email'], pub_date=datetime.now())

    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))


@login_required()
def categories(request):
    # ?Все категории
    all_categories = Category.objects.all()

    # ?Популярные статьи для сайдбара
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    # ?Категории для сайдбара
    latest_category_list = Category.objects.order_by('name')[:5]
    # ?Теги для сайдбара
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'all_categories': all_categories,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/categories.html', context)


@login_required()
def tags(request):
    # ?Все теги
    all_tags = Tag.objects.all()

    # ?Популярные статьи для сайдбара
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    # ?Категории для сайдбара
    latest_category_list = Category.objects.order_by('name')[:5]
    # ?Теги для сайдбара
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'all_tags': all_tags,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/tags.html', context)

myblog/apps/authorization/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CreateUserForm
from django.core.paginator import Paginator


def index(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        return render(request, 'index.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('authorization:login')
        else:
            form = CreateUserForm()
    return render(request, 'registration/register.html', {'form': form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            userr = authenticate(request, username=username, password=password)
            if userr is not None:
                login(request, userr)
                return redirect('articles:index')
            else:
                messages.info(request, 'Неправильный логин или пароль')
        context = {}
        return render(request, 'registration/login.html', context)

myblog/templates/articles/blog-single.html
{% extends 'base_blog.html' %}
{% load static %}

{% block login %}
    <ul class="breadcrumb">
        {% if user.is_superuser == True %}
            <li><a href="../../admin/">{{ user.username }}</a></li>
        {% else %}
            <li>{{ user.username }}</li>
        {% endif %}
        <li><a href="{% url 'authorization:logout' %}">Выйти</a></li>
    </ul>
{% endblock %}

{% block article %}
    <article><img class="img-responsive full-width" src="{% static 'images/' %}{{ article.image }}"
                  alt="">
        <div class="blog-post">
            <div class="row">
                <div class="col-md-4">

                    <!-- Post Info -->
                    <div class="post-admin text-center"><img
                            src="{% static 'images/' %}{{ article.author_name.image }}" alt="">
                        <ul>
                            <li><i class="fa fa-user"></i>
                                <p>{{ article.author_name.name }}</p>
                            </li>
                            <li><i class="fa fa-eye"></i>
                                <p>{{ article.views }} просмотра(ов)</p>
                            </li>
                            <li><i class="fa fa-clock-o"></i>
                                <p>{{ article.pub_date|date:'d F' }}</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8"><a
                        class="post-tittle margin-top-20 margin-bottom-20">{{ article.title }}</a>
                    <div style="font-size: 14px; margin-bottom: 10px; font-weight: bold; color: #66afe9">
                        Категория: {{ article.category.name }} <br> Теги: #{{ article.tag1.name }}
                    </div>
                    <p>1 part of text</p>
                </div>
                <div class="col-md-12">
                    <p>{{ article.text }}</p>
                </div>
            </div>

            <!--=======  COMMENTS =========-->
            <div class="comments">
                <h4>Комментарии </h4>
                <ul class="media-list">

                    {% if latest_comment_list %}
                        <!--=======  COMMENTS =========-->
                        {% for a in latest_comment_list %}
                            <li class="media">
                                <div class="media-left"><a href=""> <img class="media-object"
                                                                         src="{% static 'images/b-avatar-1.jpg' %}"
                                                                         alt=""> </a></div>
                                <div class="media-body">
                                    <h6 class="media-heading">{{ a.author_name }}<span> {{ a.pub_date|date:'d M - Y' }}</span>
                                    </h6>
                                    <p>{{ a.comment_text }}</p>
                                </div>
                            </li>
                        {% endfor %}


                    {% else %}
                        <p>Комментариев к этой статье пока не существуют. Станьте первым :)</p>
                    {% endif %}


                </ul>

                <!--=======  LEAVE COMMENTS =========-->
                <h4>Оставить комментарий</h4>
                <form method="post" action="{% url 'articles:leave_comment' article.id %}">
                    {% csrf_token %}
                    <span style="color: red">*Ваш комментарий появится после того как его подтвердит администрация или модераторы сайта</span>
                    <div class="row">
                        <div class="col-md-6">
                            <ul class="row">
                                <li class="col-sm-12">
                                    <label>
                                        <input type="text" class="form-control" required=""
                                               name="name" placeholder="Как тебя зовут?">
                                    </label>
                                </li>
                                <li class="col-sm-12">
                                    <label>
                                        <input type="text" class="form-control" name="email"
                                               placeholder="Email" required="">
                                    </label>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="row">
                                <li class="col-sm-12">
                                    <label>
                                                            <textarea class="form-control" name="text"
                                                                      placeholder="Текст комментария"
                                                                      required=""></textarea>
                                    </label>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-12">
                            <ul class="row">
                                <li class="col-sm-12">
                                    <button type="submit" name="do_comment" class="btn">Оставить
                                        комментарий
                                    </button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </article>
{% endblock %}

myblog/templates/articles/blog.html
{% extends 'base_blog.html' %}
{% load static %}

{% block title %} Блог на Django {% endblock %}

{% block login %}
    <ul class="breadcrumb">
        {% if user.is_superuser == True %}
            <li><a href="../admin/">{{ user.username }}</a></li>
        {% else %}
            <li>{{ user.username }}</li>
        {% endif %}
        <li><a href="{% url 'authorization:logout' %}">Выйти</a></li>
    </ul>
{% endblock %}

{% block typeOfPage %} Все статьи {% endblock %}

{% block article %}
    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <!-- Blog Artical -->
            <article><img class="img-responsive full-width" src="{% static 'images/' %}{{ a.image }}" alt="">
                <div class="blog-post">
                    <div class="row">
                        <div class="col-md-4">
                            <!-- Post Info -->
                            <div class="post-admin text-center"><img
                                    src="{% static 'images/' %}{{ a.author_name.image }}" alt="">
                                <ul>
                                    <li><i class="fa fa-user"></i>
                                        <p>{{ a.author_name.name }}</p>
                                    </li>
                                    <li><i class="fa fa-eye"></i>
                                        <p>{{ a.views }} просмотра(ов)</p>
                                    </li>
                                    <li><i class="fa fa-clock-o"></i>
                                        <p>{{ a.pub_date|date:'d F' }}</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-8"><a href="{% url 'articles:detail' a.id %}"
                                                 class="post-tittle margin-top-20 margin-bottom-20">{{ a.title }}</a>
                            <p>{{ a.text|truncatewords:50 }}</p>
                            <a href="{% url 'articles:detail' a.id %}" class="btn">Прочитать статью полностью</a></div>
                    </div>
                </div>
            </article>
        {% endfor %}
        {% if total_pages > 1 %}
            <div style="text-align: center;">
                <div class="pagination-container wow zoomIn mar-b-1x" data-wow-duration="0.5s">
                    <ul class="my_pagination">
                        {% if latest_articles_list.has_previous %}
                            <li class="my_pagination-item--wide first"><a class="my_pagination-link--wide first"
                                                                          href="{% url 'articles:index' %}?page={{ latest_articles_list.previous_page_number }}">Предыдущая</a>
                            </li>
                        {% endif %}
                        {% for p in latest_articles_list.paginator.page_range %}
                            {% if latest_articles_list.number == p %}
                                <li class="my_pagination-item is-active"><a class="my_pagination-link">{{ p }}</a></li>
                            {% elif p > latest_articles_list.number|add:-5 and p < latest_articles_list.number|add:5 %}
                                <li class="my_pagination-item"><a class="my_pagination-link"
                                                                  href="?page={{ p }}">{{ p }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if latest_articles_list.has_next %}
                            <li class="my_pagination-item--wide last"><a class="my_pagination-link--wide last"
                                                                         href="{% url 'articles:index' %}?page={{ latest_articles_list.next_page_number }}">Следующая</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% else %}
        <p>Статей в базе данных пока что не существует :(</p>
    {% endif %}
{% endblock %}

myblog/templates/articles/categories.html
{% extends 'base_blog.html' %}
{% load static %}

{% block title %} Все категории {% endblock %}

{% block login %}
    <ul class="breadcrumb">
        {% if user.is_superuser == True %}
            <li><a href="../admin/">{{ user.username }}</a></li>
        {% else %}
            <li>{{ user.username }}</li>
        {% endif %}
        <li><a href="{% url 'authorization:logout' %}">Выйти</a></li>
    </ul>
{% endblock %}

{% block typeOfPage %} Все категории {% endblock %}

{% block article %}
    {% if all_categories %}
        {% for a in all_categories %}
            {{ a.name }}
        {% endfor %}
    {% else %}
        <p>Статей в базе данных пока что не существует :(</p>
    {% endif %}
{% endblock %}

myblog/templates/articles/tags.html
{% extends 'base_blog.html' %}
{% load static %}

{% block title %} Все теги {% endblock %}

{% block login %}
    <ul class="breadcrumb">
        {% if user.is_superuser == True %}
            <li><a href="../admin/">{{ user.username }}</a></li>
        {% else %}
            <li>{{ user.username }}</li>
        {% endif %}
        <li><a href="{% url 'authorization:logout' %}">Выйти</a></li>
    </ul>
{% endblock %}

{% block typeOfPage %} Все теги {% endblock %}

{% block article %}
    {% if all_tags %}
        {% for a in all_tags %}
            {{ a.name }}
        {% endfor %}
    {% else %}
        <p>Статей в базе данных пока что не существует :(</p>
    {% endif %}
{% endblock %}