myblog/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('categories/', views.categories, name='categories'),
    path('tags/', views.tags, name='tags'),
]

myblog/apps/authorization/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'authorization'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', LogoutView.as_view(next_page='articles:index'), name='logout'),
    path('register/', views.register, name='register'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('authorization.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

myblog/apps/articles/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Category(models.Model):
    name = models.CharField('Название категории', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField('Название тега', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Author(models.Model):
    image = models.CharField('Фото автора', max_length=255, default='blog-avatar-1.png')
    name = models.CharField('Имя автора', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Article(models.Model):
    image = models.CharField('Фото статьи', max_length=255, default='blog-img-1.jpg')
    title = models.CharField('Название статьи', max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    tag1 = models.ForeignKey(Tag, on_delete=models.CASCADE, default=1)
    # tag2 = models.ForeignKey(Tag, on_delete=models.CASCADE)
    # tag3 = models.ForeignKey(Tag, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Дата публикации')
    text = models.TextField('Текс статьи')
    author_name = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    views = models.IntegerField('Просмотры', default=0)
    is_draft = models.BooleanField('Черновик', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length=50)
    comment_text = models.CharField('Текст комментария', max_length=200)
    pub_date = models.DateTimeField('Дата публикации комментария', default=datetime.now())
    email = models.CharField('Почта', max_length=255, default='unknow@mail.ru')

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

myblog/apps/authorization/models.py
from django.db import models

# Create your models here.

myblog/apps/authorization/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

myblog/apps/articles/views.py
from django.shortcuts import render
from .models import Article, Category, Tag
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage


@login_required()
def index(request):
    # ?Все статьи которые не являются черновиком
    latest_articles_list = Article.objects.filter(is_draft=False).order_by('-pub_date')
    # ?Пагинация для статей
    p = Paginator(latest_articles_list, 3)
    page_num = request.GET.get('page', 1)
    total_pages = p.num_pages  # *Это нужно для того чтобы понять, отображать нам пагинацию или нет
    # !Проверяем, существует страница или нет. На случай если человек будет играться с адресной строкой браузера
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)

    # ?Популярные статьи для сайдбара
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    # ?Категории для сайдбара
    latest_category_list = Category.objects.order_by('name')[:5]
    # ?Теги для сайдбара
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'total_pages': total_pages,
        'latest_articles_list': page,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/blog.html', context)


@login_required()
def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
        a.views = a.views + 1
        a.save()
    except:
        raise Http404("Статья не найдена!")

    latest_comment_list=a.comment_set.order_by('-id')[:10]
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    latest_category_list = Category.objects.order_by('name')[:5]
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'article': a,
        'latest_comment_list': latest_comment_list,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/blog-single.html', context)


@login_required()
def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'], email=request.POST['email'], pub_date=datetime.now())

    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))


@login_required()
def categories(request):
    # ?Все категории
    all_categories = Category.objects.all()

    # ?Популярные статьи для сайдбара
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    # ?Категории для сайдбара
    latest_category_list = Category.objects.order_by('name')[:5]
    # ?Теги для сайдбара
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'all_categories': all_categories,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/categories.html', context)


@login_required()
def tags(request):
    # ?Все теги
    all_tags = Tag.objects.all()

    # ?Популярные статьи для сайдбара
    popular_articles_list = Article.objects.filter(is_draft=False).order_by('views')[:5]
    # ?Категории для сайдбара
    latest_category_list = Category.objects.order_by('name')[:5]
    # ?Теги для сайдбара
    latest_tag_list = Tag.objects.order_by('name')[:10]

    context = {
        'all_tags': all_tags,
        'latest_category_list': latest_category_list,
        'popular_articles_list': popular_articles_list,
        'latest_tag_list': latest_tag_list,
    }
    return render(request, 'articles/tags.html', context)

myblog/apps/authorization/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CreateUserForm
from django.core.paginator import Paginator


def index(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        return render(request, 'index.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('authorization:login')
        else:
            form = CreateUserForm()
    return render(request, 'registration/register.html', {'form': form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            userr = authenticate(request, username=username, password=password)
            if userr is not None:
                login(request, userr)
                return redirect('articles:index')
            else:
                messages.info(request, 'Неправильный логин или пароль')
        context = {}
        return render(request, 'registration/login.html', context)

myblog/templates/base_blog.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Blog {% endblock %}</title>

    <!-- FONTS ONLINE -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,400italic,600,600italic,700,700italic,800,800italic,300'
          rel='stylesheet' type='text/css'>

    <!--MAIN STYLE-->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">

</head>
<body>

<!-- Page Wrap -->
<div id="wrap">

    <!-- Resume -->
    <div class="content animated bounceInUp">
        <div class="container">

            <!-- Sub Banner -->
            <div class="sub-banner">
                <h4>blog</h4>
                {% block login %}

                {% endblock %}

            </div>

            <!-- Contact -->
            <section class="defult blog">
                <div class="row">
                    <div class="col-md-8"><a class="post-tittle margin-top-20 margin-bottom-20">
                        {% block typeOfPage %}{% endblock %}</a></div>
                    <div class="col-md-9">
                        {% block article %} {% endblock %}
                    </div>

                    <!-- Right Sidebar -->
                    <div class="col-md-3">
                        <div class="blog-side-bar">
                            <!-- Search -->
                            <div class="search margin-bottom-30">
                                <div class="form-group">
                                    <input id="search" type="search" class="input" placeholder="Поиск..">
                                    <button class="sea-icon"><i class="fa fa-search"></i></button>
                                </div>
                            </div>

                            <!-- TAGS -->
                            <div class="cate margin-top-40">
                                <h5><a href="{% url 'articles:categories' %}">Категории</a></h5>
                                <hr>
                                <ul>
                                    {% if latest_category_list %}
                                        {% for a in latest_category_list %}
                                            <li><a href="{# ! АЙДИШНИК КАТЕГОРИИ #}">{{ a.name }} <span>(25)</span></a></li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>

                            <!-- POST -->
                            <div class="papu-post margin-top-40">
                                <h5>Популярные статьи</h5>
                                <hr>
                                <ul>
                                    {% if popular_articles_list %}
                                        {% for b in popular_articles_list %}
                                            <li class="media">
                                                <div class="media-left"><a href="{% url 'articles:detail' b.id %}"> <img class="media-object" src="
                                                        {% static 'images/' %}{{ b.image }}" alt=""></a></div>
                                                <div class="media-body"><a class="media-heading"
                                                                           href="{% url 'articles:detail' b.id %}">{{ b.title }} </a>
                                                    <span>{{ b.pub_date|date:'M d, Y' }}</span></div>
                                            </li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                            <!-- TAGS -->
                            <div class="tags margin-top-40">
                                <h5><a href="{% url 'articles:tags' %}">Теги</a></h5>
                                <hr>
                                <ul>
                                    {% if latest_tag_list %}
                                        {% for c in latest_tag_list %}
                                            <li><a href="{# ! АЙДИШНИК ТЕГА #}">{{ c.name }} </a></li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                            <!-- TAGS -->
                            <div class="cate margin-top-40">
                                <h5>Реклама</h5>
                                <hr>
                                <p>Здесь могла бы быть ваша реклама :D </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<!-- Wrap End -->
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/counter.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

myblog/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple Auth</title>
    <link rel="stylesheet" href="{% static 'css/auth_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
{% block content %}
    <div class="form_wrapper">
        <div class="form_container">
            {% if user.is_authenticated %}
                <h1>Упс... А как вы сюда попали?</h1>
                <p>Вы уже вошли на этом сайте под пользователем {{ user.username }}</p>
                <div class="button"><a href="{% url 'authorization:logout' %}" class="button" >Выйти с аккаунта (LogOut)</a></div>
                <div class="button"><a href="{% url 'articles:index' %}">Вернуться к блогу</a></div>
            {% else %}
                <h1>Выберите действие</h1>
                <div class="button"><a href="{% url 'authorization:login' %}" class="button" >Войти</a></div>
                <div class="button"><a href="{% url 'authorization:register' %}" class="button" >Зарегистрироваться</a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth_js.js' %}"></script>
</body>
</html>